// 포트폴리오 자료 저장
var app = new Vue({
	el: '#siteList',
	data: {
		sites : [
		{siteId : 1,sortClass:'cr_box desktop',img :'images/cr_list06.jpg',siteName :'PUBJ 포트폴리오',subScript :'신규 웹사이트',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_desktop" title="Desktop Web"></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',	viewHref : 'ajax/pubj.html',goHref :'http://www.pubj.co.kr',tKind :'_blank'},
		{siteId : 2,sortClass:'cr_box desktop',img :'images/cr_list01.jpg',siteName :'서울소방재난본부',subScript :'웹사이트 리뉴얼',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_desktop" title="Desktop Web"></i></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',viewHref : 'ajax/fire.html',goHref :'http://www.pubj.co.kr/portfolio/fire.seoul.go.kr',tKind :'_blank'},
		{siteId : 3,sortClass:'cr_box desktop mobile resp',img :'images/cr_list02.jpg',siteName :'동대문디자인페어',subScript :'반응형 웹사이트',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_desktop" title="Desktop Web"></i><i class="ico_type ico_mobile" title="Mobile Web"></i><i class="ico_type ico_resp" title="Responsive Web"></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',viewHref : 'ajax/ddp.html',goHref :'http://www.pubj.co.kr/portfolio/ddpdesignfair.or.kr',tKind :'_blank'},
		{siteId : 4,sortClass:'cr_box mobile',img :'images/cr_list03.jpg',siteName :'영풍문고',subScript :'모바일웹 리뉴얼',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_mobile" title="Mobile Web"></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',viewHref : 'ajax/ypbooks.html',goHref :"javascript:void(window.open('http://www.pubj.co.kr/portfolio/ypbooks.co.kr/index.html','','width=360, height=640, left=100, top=50, scrollbars=0, toolbar=0, menubar=no'))",tKind :'_self'},
		{siteId : 5,sortClass:'cr_box desktop',img :'images/cr_list04.jpg',siteName :'투썸플레이스',subScript :'웹사이트 리뉴얼',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_desktop" title="Desktop Web"></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',viewHref : 'ajax/twosome.html',goHref :'http://www.pubj.co.kr/portfolio/twosome.co.kr',tKind :'_blank'},
		{siteId : 6,sortClass:'cr_box desktop',img :'images/cr_list05.jpg',siteName :'현대하이홈인테리어',subScript :'웹사이트 리뉴얼',myRole :'CODING : 100% / DESIGN : 100%',siteType : '<i class="ico_type ico_desktop" title="Desktop Web"></i><i class="ico_type ico_mobile" title="Mobile Web"></i><i class="ico_type ico_resp" title="Responsive Web"></i>',bw :'<i class="ico_browser ico_chrome"></i> <i class="ico_browser ico_firefox"></i> <i class="ico_browser ico_ie"></i> <i class="ico_browser ico_opera"></i>',viewHref : 'ajax/hhh.html',goHref :'http://www.pubj.co.kr/portfolio/hyundaihihome.nasoft.kr',tKind :'_blank'}
		]
	}
});